# Generated by Django 2.0 on 2017-12-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short',
            field=models.CharField(default=1, max_length=450),
            preserve_default=False,
        ),
    ]
