# Generated by Django 2.0 on 2017-12-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short',
        ),
        migrations.AddField(
            model_name='post',
            name='short_desc',
            field=models.TextField(default=1, max_length=450),
            preserve_default=False,
        ),
    ]
