# Generated by Django 2.0 on 2017-12-27 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171227_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='short_desc',
            new_name='short_description',
        ),
    ]
