# Generated by Django 2.0 on 2017-12-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171227_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='A short label, generally used in URLs.', max_length=250, unique_for_date='publish'),
        ),
    ]
